name: echelon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  purchases_flutter: ^9.10.0
  dotenv: ^4.2.0
  flutter_dotenv: ^6.0.0
  sign_in_with_apple: ^7.0.1
  record: ^6.1.2
  audioplayers: ^6.5.1
  http: ^1.6.0
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3
  hive_ce_generator: ^1.11.0
  build_runner: ^2.10.4
  provider: ^6.1.5+1
  uuid: ^4.5.1
  flutter_markdown: ^0.7.4+1
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true